### PR TITLE
Added retry strategy

### PR DESCRIPTION
**Pull request by tyler-horschig**

### CODE REVIEW

**Comment by dgopani-crest** [comment]
Hi @dedsec594, Can you please verify the latest changes and give your approval so we will move further for release activities

**Review by tyler-horschig — COMMENTED** [review]
Looks good

**Review by tyler-horschig — COMMENTED** [review]
looks good

**Review by tyler-horschig — COMMENTED** [review]
looks good

**Review by rgil-splunk — APPROVED** [review]

**Pull request merged**
